services:
  bot:
    image: anvelope/bot:latest
    build: .
    ports:
      - 8007:3000
    environment:
      - TOKEN=${TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - PORT=${PORT}
    # env_file:
    #   - .env
